// Generated by CoffeeScript 1.6.3
(function() {
  var TerminalToHTML, WebSocketServer, app, broadcast, child_process, express, fs, rootDir, startServer, wss, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  child_process = require('child_process');

  express = require('express');

  app = express();

  app.use('/public', express["static"](__dirname + '/public'));

  WebSocketServer = require('ws').Server;

  wss = new WebSocketServer({
    port: 7001
  });

  broadcast = function(msg) {
    var client, _i, _len, _ref, _results;
    _ref = wss.clients;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      client = _ref[_i];
      _results.push(client.send(msg));
    }
    return _results;
  };

  startServer = function() {
    app.listen(7000);
    return console.log('Open http://localhost:7000 in Chrome\nPress Ctrl+C to exit');
  };

  TerminalToHTML = (function() {
    var lineEnd, lineStart, _ref;

    _ref = ['<div>', '</div>'], lineStart = _ref[0], lineEnd = _ref[1];

    function TerminalToHTML(_yield, textcolor, background, buffer) {
      this["yield"] = _yield != null ? _yield : (function() {});
      this.textcolor = textcolor != null ? textcolor : '';
      this.background = background != null ? background : '';
      this.buffer = buffer != null ? buffer : '';
      this.write = __bind(this.write, this);
    }

    TerminalToHTML.prototype.write = function(data) {
      var line, lines, _i, _len, _results;
      this.buffer += data.toString();
      lines = this.buffer.split('\n');
      this.buffer = lines.pop();
      _results = [];
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        this["yield"](lineStart);
        this["yield"](line);
        _results.push(this["yield"](lineEnd));
      }
      return _results;
    };

    return TerminalToHTML;

  })();

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/public/client.html');
  });

  rootDir = (_ref = process.argv[2]) != null ? _ref : '.';

  app.get('/command', function(req, res) {
    var command, gcc, rewriter;
    if (!(command = req.query.q)) {
      return res.send(400);
    }
    res.writeHead(200);
    rewriter = new TerminalToHTML(function(html) {
      return res.write(html);
    });
    gcc = child_process.spawn('bash', ['-c', command], {
      cwd: rootDir
    });
    gcc.stdout.on('data', rewriter.write);
    gcc.stderr.on('data', rewriter.write);
    gcc.on('close', function() {
      return res.end();
    });
    return gcc.stdin.end();
  });

  fs.watch(rootDir, {
    interval: 500
  }, function() {
    return broadcast('reload');
  });

  startServer();

}).call(this);
